name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build ./LeaveTracker/LeaveTracker.sln --configuration Release
      - name: Test
        run: dotnet test ./LeaveTracker/LeaveTracker.sln --no-build --configuration Release